### PR TITLE
Improved headers on the home and book pages

### PR DESCRIPTION
**Pull request by SashaKryzh**

### CODE REVIEW

**Comment by denitdao** [comment]
Looks nice! Thanks for improving button and headers. 
Could you fix title issue on mobile
image

**Comment by SashaKryzh** [comment]
@denitdao fixed

**Comment by SashaKryzh** [comment]
hmmm... what tool do you use to simulate Pixel 7? I usually start Android simulator and use browser inside of it, but I guess it's not the best option

**Comment by denitdao** [comment]
Dev tools do the job for me :) 

https://developer.chrome.com/docs/devtools/device-mode

**Comment by denitdao** [comment]
LGTM now, thanks

**Pull request merged**
